before_build:
  - nuget restore Rocket-Handicraft\Rocket-Handicraft.sln

configuration: Release  
  
build:
  project: Rocket-Handicraft\Rocket-Handicraft.sln
  
artifacts:
  - path: Rocket-Handicraft\bin\$(configuration)
    name: Rocket-Handicraf
